//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    
    public partial class spres_get1cam
    {
        public int Id { get; set; }
        public bool IsApprovedbyAdmin { get; set; }
        public string storyDescription { get; set; }
        public string DPPath { get; set; }
    }
}
