//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LoanBankDetails
    {
        public int id { get; set; }
        public Nullable<int> StoryId { get; set; }
        public string BenName { get; set; }
        public string AccountNumber { get; set; }
        public string IFSC { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> IsApprovedByAdmin { get; set; }
        public Nullable<int> IsRejectedByAdmin { get; set; }
        public string RejectedReason { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    }
}
