//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lookup
    {
        public int id { get; set; }
        public string LookupKey { get; set; }
        public string LookupValue { get; set; }
    }
}
