//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_search
    {
        public string PK_Column { get; set; }
        public string Column_Value { get; set; }
        public string Column_Name { get; set; }
        public string KeyWord { get; set; }
        public string Table_Schema { get; set; }
        public string Table_Name { get; set; }
    }
}
