//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LoanShares
    {
        public int ShareID { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public int StoryId { get; set; }
        public string Media { get; set; }
    }
}
