//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LoanWithdrawRequest
    {
        public int id { get; set; }
        public decimal withdrawalAmount { get; set; }
        public string withdrawReason { get; set; }
        public string withdrawStatus { get; set; }
        public Nullable<int> StoryId { get; set; }
        public string createdby { get; set; }
        public string Updateddby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> bankId { get; set; }
        public Nullable<int> IsApprovedByAdmin { get; set; }
        public Nullable<int> isWithdrawn { get; set; }
        public Nullable<int> IsRejectedByAdmin { get; set; }
        public string RejectedReason { get; set; }
        public Nullable<System.DateTime> Approvedon { get; set; }
    }
}
