//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_searchResult
    {
        public int id { get; set; }
        public Nullable<int> PKColumn { get; set; }
        public string ColumnValue { get; set; }
        public string ColumnName { get; set; }
        public string TableSchema { get; set; }
        public string TableName { get; set; }
        public string Keyword { get; set; }
    }
}
