//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserNGOEndorsement
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string NGORegisterationNO { get; set; }
        public string NGORegAt { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> NGOSector { get; set; }
        public Nullable<int> NGOType { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
