//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace firstWebAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Endorse
    {
        public int EndorseID { get; set; }
        public int NGOId { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public int CampaignId { get; set; }
    
        public virtual Tbl_Campaign Tbl_Campaign { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
